"use client";

import { useRef, useMemo, useState, useCallback, useEffect } from "react";
import { buildTeacherGraph, getTeacherConnectedSlugs } from "@/lib/teacher-graph";
import type { Teacher } from "@/lib/types";
import type { LayoutMap } from "@/lib/compute-layout";
import { useMapZoom } from "@/components/tradition-map/use-map-zoom";
import { TeacherMapNode } from "./teacher-map-node";
import { TeacherMapEdge } from "./teacher-map-edge";
import { TeacherMapPopover } from "./teacher-map-popover";
import { TeacherTimeAxis } from "./teacher-time-axis";

// Pre-computed layout generated by `npm run prebuild`
import layoutData from "@/generated/teacher-map-layout.json";

interface TeacherMapProps {
  teachers: Teacher[];
}

function computeViewBox(layout: LayoutMap) {
  const positions = Object.values(layout);
  if (positions.length === 0) return { x: 0, y: 0, width: 1000, height: 800 };
  const xs = positions.map((p) => p.x);
  const ys = positions.map((p) => p.y);
  const pad = 100;
  return {
    x: Math.min(...xs) - pad,
    y: Math.min(...ys) - pad,
    width: Math.max(...xs) - Math.min(...xs) + pad * 2,
    height: Math.max(...ys) - Math.min(...ys) + pad * 2,
  };
}

export function TeacherMap({ teachers }: TeacherMapProps) {
  const svgRef = useRef<SVGSVGElement>(null);
  const layout = layoutData as LayoutMap;

  const graph = useMemo(() => buildTeacherGraph(teachers), [teachers]);
  const { transform } = useMapZoom(svgRef);
  const viewBox = useMemo(() => computeViewBox(layout), [layout]);

  const [hoveredSlug, setHoveredSlug] = useState<string | null>(null);
  const [selectedSlug, setSelectedSlug] = useState<string | null>(null);
  const activeSlug = hoveredSlug ?? selectedSlug;
  const nodeHideTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const connectedSlugs = useMemo(
    () => (activeSlug ? getTeacherConnectedSlugs(graph, activeSlug) : new Set<string>()),
    [graph, activeSlug]
  );

  const handleNodeHover = useCallback((slug: string | null) => {
    if (nodeHideTimer.current) {
      clearTimeout(nodeHideTimer.current);
      nodeHideTimer.current = null;
    }
    if (slug) {
      setHoveredSlug(slug);
    } else {
      nodeHideTimer.current = setTimeout(() => setHoveredSlug(null), 300);
    }
  }, []);

  const handleNodeClick = useCallback((slug: string) => {
    setSelectedSlug((prev) => (prev === slug ? null : slug));
    setHoveredSlug(null);
  }, []);

  const handlePopoverEnter = useCallback(() => {
    if (nodeHideTimer.current) {
      clearTimeout(nodeHideTimer.current);
      nodeHideTimer.current = null;
    }
  }, []);

  const handlePopoverLeave = useCallback(() => {
    nodeHideTimer.current = setTimeout(() => setHoveredSlug(null), 200);
  }, []);

  const handleDeselect = useCallback(() => setSelectedSlug(null), []);

  const handleSvgClick = useCallback(
    (e: React.MouseEvent<SVGSVGElement>) => {
      if (e.target === e.currentTarget) handleDeselect();
    },
    [handleDeselect]
  );

  // Clear selection when active slug's node is no longer in graph
  useEffect(() => {
    if (selectedSlug && !graph.nodes.find((n) => n.slug === selectedSlug)) {
      const t = setTimeout(() => setSelectedSlug(null), 0);
      return () => clearTimeout(t);
    }
  }, [graph, selectedSlug]);

  const isHighlighted = useCallback(
    (slug: string) => slug === activeSlug,
    [activeSlug]
  );

  const isDimmed = useCallback(
    (slug: string) => !!(activeSlug && slug !== activeSlug && !connectedSlugs.has(slug)),
    [activeSlug, connectedSlugs]
  );

  const isEdgeHighlighted = useCallback(
    (src: string, tgt: string) =>
      !!(activeSlug && (src === activeSlug || tgt === activeSlug)),
    [activeSlug]
  );

  const isEdgeDimmed = useCallback(
    (src: string, tgt: string) =>
      !!(activeSlug && src !== activeSlug && tgt !== activeSlug),
    [activeSlug]
  );

  const ys = Object.values(layout).map((p) => p.y);
  const xs = Object.values(layout).map((p) => p.x);
  const yMin = Math.min(...ys);
  const yMax = Math.max(...ys);
  const xMin = Math.min(...xs);
  const xMax = Math.max(...xs);

  return (
    <div className="w-full">
      <style>{`
        @keyframes teacher-fade-in {
          from { opacity: 0; transform: translateY(-4px); }
          to { opacity: 1; transform: translateY(0); }
        }
      `}</style>

      <div className="relative bg-white rounded-lg shadow-sm">
        <svg
          ref={svgRef}
          className="w-full h-auto"
          viewBox={`${viewBox.x} ${viewBox.y} ${viewBox.width} ${viewBox.height}`}
          style={{ maxHeight: "80vh", minHeight: "65vh", touchAction: "none" }}
          aria-label="Interactive map of teacher lineages"
          role="img"
          onClick={handleSvgClick}
        >
          {/* Arrow marker definition */}
          <defs>
            <marker
              id="teacher-arrow"
              markerWidth="8"
              markerHeight="8"
              refX="6"
              refY="3"
              orient="auto"
            >
              <path d="M0,0 L0,6 L8,3 z" fill="rgba(160,115,70,0.7)" />
            </marker>
          </defs>

          <g transform={`translate(${transform.x}, ${transform.y}) scale(${transform.k})`}>
            {/* Layer 1: Time axis */}
            <TeacherTimeAxis
              labelX={xMin - 80}
              gridXStart={xMin - 10}
              gridXEnd={xMax + 50}
              yMin={yMin - 10}
              yMax={yMax + 10}
            />

            {/* Layer 2: Edges */}
            {graph.edges.map((edge) => {
              const src = layout[edge.source];
              const tgt = layout[edge.target];
              if (!src || !tgt) return null;
              const key = `${edge.source}--${edge.target}`;
              return (
                <TeacherMapEdge
                  key={key}
                  edgeKey={key}
                  sourcePos={src}
                  targetPos={tgt}
                  highlighted={isEdgeHighlighted(edge.source, edge.target)}
                  dimmed={isEdgeDimmed(edge.source, edge.target)}
                />
              );
            })}

            {/* Layer 3: Nodes */}
            {graph.nodes.map((node) => {
              const pos = layout[node.slug];
              if (!pos) return null;
              return (
                <TeacherMapNode
                  key={node.slug}
                  node={node}
                  position={pos}
                  highlighted={isHighlighted(node.slug)}
                  dimmed={isDimmed(node.slug)}
                  zoomScale={transform.k}
                  onHover={handleNodeHover}
                  onClick={handleNodeClick}
                />
              );
            })}

            {/* Layer 4: Popover */}
            {activeSlug && (() => {
              const node = graph.nodes.find((n) => n.slug === activeSlug);
              const pos = node ? layout[node.slug] : null;
              if (!node || !pos) return null;
              return (
                <TeacherMapPopover
                  node={node}
                  position={pos}
                  onClose={handleDeselect}
                  onPopoverEnter={handlePopoverEnter}
                  onPopoverLeave={handlePopoverLeave}
                />
              );
            })()}
          </g>
        </svg>

        {/* Legend */}
        <div className="absolute bottom-3 right-3 flex items-center gap-2 text-xs font-sans text-muted-foreground bg-white/80 backdrop-blur-sm rounded px-3 py-1.5 border border-border/50">
          <svg width="24" height="12" viewBox="0 0 24 12">
            <path d="M0,10 C0,5 24,5 24,2" stroke="rgb(160,115,70)" strokeWidth="1.5" fill="none" markerEnd="url(#teacher-arrow-legend)" />
            <defs>
              <marker id="teacher-arrow-legend" markerWidth="6" markerHeight="6" refX="5" refY="2" orient="auto">
                <path d="M0,0 L0,4 L6,2 z" fill="rgb(160,115,70)" />
              </marker>
            </defs>
          </svg>
          studied under
        </div>
      </div>
    </div>
  );
}
